AttributeError: 'Command' object has no attribute 'option_list'
There is a bug in the command in which option_list doesn't exist and thus, cannot be added to.